/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./buyers-megamenu.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--ds-font-family-primary)"],
        ds: ["var(--ds-font-family-primary)"],
      },
      colors: {
        ds: {
          purple: {
            50: "var(--ds-color-purple-50)",
            100: "var(--ds-color-purple-100)",
            200: "var(--ds-color-purple-200)",
            300: "var(--ds-color-purple-300)",
            400: "var(--ds-color-purple-400)",
            500: "var(--ds-color-purple-500)",
            600: "var(--ds-color-purple-600)",
            700: "var(--ds-color-purple-700)",
            800: "var(--ds-color-purple-800)",
            900: "var(--ds-color-purple-900)",
          },
          "warm-neutral": {
            0: "var(--ds-color-warm-neutral-0)",
            50: "var(--ds-color-warm-neutral-50)",
            100: "var(--ds-color-warm-neutral-100)",
            200: "var(--ds-color-warm-neutral-200)",
            300: "var(--ds-color-warm-neutral-300)",
            400: "var(--ds-color-warm-neutral-400)",
            500: "var(--ds-color-warm-neutral-500)",
            600: "var(--ds-color-warm-neutral-600)",
            700: "var(--ds-color-warm-neutral-700)",
            800: "var(--ds-color-warm-neutral-800)",
            900: "var(--ds-color-warm-neutral-900)",
          },
          "grey-neutral": {
            0: "var(--ds-color-grey-neutral-0)",
            50: "var(--ds-color-grey-neutral-50)",
            100: "var(--ds-color-grey-neutral-100)",
            200: "var(--ds-color-grey-neutral-200)",
            300: "var(--ds-color-grey-neutral-300)",
            400: "var(--ds-color-grey-neutral-400)",
            500: "var(--ds-color-grey-neutral-500)",
            600: "var(--ds-color-grey-neutral-600)",
            700: "var(--ds-color-grey-neutral-700)",
            800: "var(--ds-color-grey-neutral-800)",
            900: "var(--ds-color-grey-neutral-900)",
          },
          pink: {
            50: "var(--ds-color-pink-50)",
            100: "var(--ds-color-pink-100)",
            200: "var(--ds-color-pink-200)",
            300: "var(--ds-color-pink-300)",
            400: "var(--ds-color-pink-400)",
            500: "var(--ds-color-pink-500)",
            600: "var(--ds-color-pink-600)",
            700: "var(--ds-color-pink-700)",
            800: "var(--ds-color-pink-800)",
            900: "var(--ds-color-pink-900)",
          },
          blue: {
            50: "var(--ds-color-blue-50)",
            100: "var(--ds-color-blue-100)",
            200: "var(--ds-color-blue-200)",
            300: "var(--ds-color-blue-300)",
            400: "var(--ds-color-blue-400)",
            500: "var(--ds-color-blue-500)",
            600: "var(--ds-color-blue-600)",
            700: "var(--ds-color-blue-700)",
            800: "var(--ds-color-blue-800)",
            900: "var(--ds-color-blue-900)",
          },
          yellow: {
            50: "var(--ds-color-yellow-50)",
            100: "var(--ds-color-yellow-100)",
            200: "var(--ds-color-yellow-200)",
            300: "var(--ds-color-yellow-300)",
            400: "var(--ds-color-yellow-400)",
            500: "var(--ds-color-yellow-500)",
            600: "var(--ds-color-yellow-600)",
            700: "var(--ds-color-yellow-700)",
            800: "var(--ds-color-yellow-800)",
            900: "var(--ds-color-yellow-900)",
          },
          green: {
            50: "var(--ds-color-green-50)",
            100: "var(--ds-color-green-100)",
            200: "var(--ds-color-green-200)",
            300: "var(--ds-color-green-300)",
            400: "var(--ds-color-green-400)",
            500: "var(--ds-color-green-500)",
            600: "var(--ds-color-green-600)",
            700: "var(--ds-color-green-700)",
            800: "var(--ds-color-green-800)",
            900: "var(--ds-color-green-900)",
          },
          red: {
            50: "var(--ds-color-red-50)",
            100: "var(--ds-color-red-100)",
            200: "var(--ds-color-red-200)",
            300: "var(--ds-color-red-300)",
            400: "var(--ds-color-red-400)",
            500: "var(--ds-color-red-500)",
            600: "var(--ds-color-red-600)",
            700: "var(--ds-color-red-700)",
            800: "var(--ds-color-red-800)",
            900: "var(--ds-color-red-900)",
          },
          "pistachio-sand": {
            50: "var(--ds-color-pistachio-sand-50)",
            100: "var(--ds-color-pistachio-sand-100)",
            200: "var(--ds-color-pistachio-sand-200)",
            300: "var(--ds-color-pistachio-sand-300)",
            400: "var(--ds-color-pistachio-sand-400)",
            500: "var(--ds-color-pistachio-sand-500)",
          },
          "lavender-mist": {
            50: "var(--ds-color-lavender-mist-50)",
            100: "var(--ds-color-lavender-mist-100)",
            200: "var(--ds-color-lavender-mist-200)",
            300: "var(--ds-color-lavender-mist-300)",
            400: "var(--ds-color-lavender-mist-400)",
            500: "var(--ds-color-lavender-mist-500)",
          },
          "soft-butter": {
            50: "var(--ds-color-soft-butter-50)",
            100: "var(--ds-color-soft-butter-100)",
            200: "var(--ds-color-soft-butter-200)",
            300: "var(--ds-color-soft-butter-300)",
            400: "var(--ds-color-soft-butter-400)",
            500: "var(--ds-color-soft-butter-500)",
          },
          surface: {
            white: "var(--ds-surface-white)",
            subtle: "var(--ds-surface-subtle)",
            default: "var(--ds-surface-default)",
            brand: "var(--ds-surface-brand)",
            "brand-subtle": "var(--ds-surface-brand-subtle)",
            disabled: "var(--ds-surface-disabled)",
          },
          border: {
            subtle: "var(--ds-border-subtle)",
            default: "var(--ds-border-default)",
            brand: "var(--ds-border-brand)",
            selected: "var(--ds-border-selected)",
            disabled: "var(--ds-border-disabled)",
          },
          text: {
            primary: "var(--ds-text-primary)",
            secondary: "var(--ds-text-secondary)",
            muted: "var(--ds-text-muted)",
            inverse: "var(--ds-text-inverse)",
            brand: "var(--ds-text-brand)",
          },
          highlight: "var(--ds-highlight)",
        },
      },
      spacing: {
        "ds-none": "var(--ds-space-none)",
        "ds-3xs": "var(--ds-space-3xs)",
        "ds-2xs": "var(--ds-space-2xs)",
        "ds-xs": "var(--ds-space-xs)",
        "ds-s": "var(--ds-space-s)",
        "ds-m": "var(--ds-space-m)",
        "ds-l": "var(--ds-space-l)",
        "ds-xl": "var(--ds-space-xl)",
        "ds-2xl": "var(--ds-space-2xl)",
        "ds-3xl": "var(--ds-space-3xl)",
        "ds-4xl": "var(--ds-space-4xl)",
        "ds-5xl": "var(--ds-space-5xl)",
        "ds-6xl": "var(--ds-space-6xl)",
        "ds-7xl": "var(--ds-space-7xl)",
        "ds-8xl": "var(--ds-space-8xl)",
      },
      borderRadius: {
        "ds-none": "var(--ds-radius-none)",
        "ds-xs": "var(--ds-radius-xs)",
        "ds-s": "var(--ds-radius-s)",
        "ds-m": "var(--ds-radius-m)",
        "ds-l": "var(--ds-radius-l)",
        "ds-xl": "var(--ds-radius-xl)",
        "ds-2xl": "var(--ds-radius-2xl)",
        "ds-3xl": "var(--ds-radius-3xl)",
        "ds-full": "var(--ds-radius-full)",
      },
      fontSize: {
        "ds-xs": ["var(--ds-font-size-xs)", { lineHeight: "var(--ds-line-height-xs)" }],
        "ds-s": ["var(--ds-font-size-s)", { lineHeight: "var(--ds-line-height-s)" }],
        "ds-m": ["var(--ds-font-size-m)", { lineHeight: "var(--ds-line-height-m)" }],
        "ds-lg": ["var(--ds-font-size-lg)", { lineHeight: "var(--ds-line-height-l)" }],
        "ds-xl": ["var(--ds-font-size-xl)", { lineHeight: "var(--ds-line-height-xl)" }],
        "ds-2xl": ["var(--ds-font-size-2xl)", { lineHeight: "var(--ds-line-height-2xl)" }],
        "ds-3xl": ["var(--ds-font-size-3xl)", { lineHeight: "var(--ds-line-height-3xl)" }],
        "ds-4xl": ["var(--ds-font-size-4xl)", { lineHeight: "var(--ds-line-height-4xl)" }],
        "ds-5xl": ["var(--ds-font-size-5xl)", { lineHeight: "var(--ds-line-height-5xl)" }],
        "ds-6xl": ["var(--ds-font-size-6xl)", { lineHeight: "var(--ds-line-height-6xl)" }],
        "ds-7xl": ["var(--ds-font-size-7xl)", { lineHeight: "var(--ds-line-height-7xl)" }],
        "ds-8xl": ["var(--ds-font-size-8xl)", { lineHeight: "var(--ds-line-height-8xl)" }],
        "ds-9xl": ["var(--ds-font-size-9xl)", { lineHeight: "var(--ds-line-height-9xl)" }],
      },
    },
  },
  plugins: [],
};
